---
- name: (re)start pgmailer container
  docker_container:
    name: "{{pgmailer_docker_name}}"
    image: "{{pgmailer_docker_image}}"
    network_mode: host
    env:
      PGHOST: "{{pgmailer_pghost}}"
      PGDATABASE: "{{pgmailer_pgdatabase}}"
      PGUSER: "{{pgmailer_pguser}}"
      PGPASSWORD: "{{pgmailer_pgpassword}}"
      SMTP_HOST: "{{pgmailer_smtp_host}}"
      SMTP_LOGIN: "{{pgmailer_smtp_login}}"
      SMTP_PASSWORD: "{{pgmailer_smtp_password}}"
      LOGLEVEL: "{{pgmailer_loglevel}}"
    restart_policy: always
    restart: "{{__pgmailer_restart | default(false)}}"
    pull: true
    state: "started"
